# Generated by Django 5.0 on 2023-12-18 14:15

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_conversation_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='gptresponse',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
