# Generated by Django 5.0 on 2023-12-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_gptresponse_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptresponse',
            name='conversation',
        ),
    ]
