# Generated by Django 5.0 on 2023-12-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_gptresponse_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptresponse',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversation'),
        ),
    ]
